### ISSUE TITLE
Connection to key server

### ISSUE THREAD

**Issue by toberndo** [mailvelope/mailvelope#10]
- find keys on key server, direct import
- automatic retrieval in encrypt dialog (non-persistent)?

**Comment by eeach** [comment]
+1

**Comment by MatthewWest** [comment]
+1

**Comment by HibikiTaisuna** [comment]
+1

**Comment by Manouchehri** [comment]
It would also be helpful if when I go to reply to an email, if Mailvelope would point out that the receiver actually has a PGP key. At the moment I have to manually check for each person, which is a bit time consuming.

I will probably look into this myself in the future, but I'm not sure if my Chrome skills are up there.

**Comment by Coy0te** [comment]
+1 ! 

Integrating auto-request of a few preconfigured keyservers would make this tool one step closer to THE perfect PGP browser add-on.

**Comment by hendrixski** [comment]
+1   

Except they keyserver should be Keybase.io

Mailvelope + keybase = world domination.

**Comment by Pablohn26** [comment]
+1

**Comment by PiNotEqual3** [comment]
+1 must have!
Just got a bunch of encrypted mails and need manually search and add the keys. What a nightmare...

**Comment by petrusek** [comment]
+1

**Comment by dashohoxha** [comment]
It seems to me that there are some misconceptions in the discussions in this thread:

```
automatic retrieval in encrypt dialog (non-persistent)?
```
It is wrong to encrypt all the outgoing emails, without the consent of the recipent. Some people may have lost their private key (or forgoten its password). In this case you are just sending them garbage. Some other people (like me), don't want to get all the emails encrypted, because they save most of the emails in order to search them later.

```
It would also be helpful if when I go to reply to an email, if Mailvelope would point out that the receiver actually has a PGP key. At the moment I have to manually check for each person, which is a bit time consuming.
```
Some people may have more than one PGP key, which one would you use? And again, how would you know that people still have access to their keys?

In my case, when I want to show to the others that I am willing to accept encrypted emails, I attach my public key to the message and sign the message with the corresponding private key (I have more than one key).

```
Except they keyserver should be Keybase.io
```
I don't agree. Keybase.io is just an extended/enhanced keyserver, so it must be compatible with all the other keyservers and must synchronize its data with them. So, we can pick up any keyserver and should be able to find there Keybase.io users as well, or we can pick up Keybase and we should find there all gpg users.

```
Just got a bunch of encrypted mails and need manually search and add the keys. What a nightmare...
```
This is just a bullshit. For decrypting messages you need to import your own private keys, what nightmare are you talking about? If you got a bunch of gpg **signed** emails, this is a different issue.

**Comment by Manouchehri** [comment]
@dashohoxha You're supposed to set a subkey (or master key) expiration date to avoid the situation of having a non-accessible key looking valid. Or, create the revocation certificate in advanced.

Mailvelope won't let you encrypt mail to an expired or revoked key/subkey.

**Comment by dashohoxha** [comment]
@Manouchehri Despite of what is being supposed, I have lost my keys on the past, and I am a computer expert. Am I an exception? I don't think so. And I have seen a lot of people that do not even set an expiration date on their keys.

**Comment by Manouchehri** [comment]
If you follow any reasonable tutorial, it will tell you about revocation certificates. Ultimately I think it's fair for the default behavior to assume that users can follow a basic tutorial correctly.

Examples:

https://wiki.archlinux.org/index.php/GnuPG#Revoking_a_key
https://www.gnupg.org/gph/en/manual/c14.html

You're describing an inherit problem with PGP, and it isn't fixable. S/MIME has the same issue (except there's a central authority who can revoke your certificate). You may be more interested in OTRv3 if PGP is too difficult.

**Comment by dashohoxha** [comment]
On Tue, Jan 12, 2016 at 4:18 PM, David Manouchehri <notifications@github.com
> wrote:

> If you follow any reasonable tutorial, it will tell you about revocation
> certificates. Ultimately I think it's fair for the default behavior to
> assume that users can follow a basic tutorial correctly.
>
Ok, put on the wall of shame, I don't mind.
Do you have any statistics about how many people have or have had problems
with their keys?

You're describing an inherit problem with PGP, and it isn't fixable. S/MIME
> has the same issue (except there's a central
>
If you agree that managing GPG keys is a problem and it is inherently
difficult, then what is the point of discussing?

> authority who can revoke your certificate). You may be more interested in
> OTRv3 if PGP is too difficult.
>
Now you are going completely out of topic.

**Comment by Manouchehri** [comment]
That would be a neat experiment to see how many people still can use PGP after uploading their public key. I haven't seen any previous research on it.

I don't think anyone considers PGP keys to be an easy concept for beginners. I feel there's no need to get into a usability debate since there's a lot of smarter people than me who have written about it.

http://www.cs.berkeley.edu/~tygar/papers/Why_Johnny_Cant_Encrypt/USENIX.pdf
https://www.schneier.com/blog/archives/2015/11/testing_the_usa.html
https://blog.whitehatsec.com/pgp-still-hard-to-use-after-16-years/

Just a reminder, we're talking about the *default* behavior. You should still be able to pick a different key or opt-out completely. However, opportunistic encryption should be a goal to aim for.

I realized I never replied to your comment about multiple keys; the usual process is to pick the key that has the expiry date furthest away. Likewise with subkeys.

https://github.com/keybase/keybase-issues/issues/1853

**Comment by dashohoxha** [comment]
@Manouchehri 

-----BEGIN PGP MESSAGE-----
Version: Mailvelope v1.3.3
Comment: https://www.mailvelope.com

wcFMA07ExxoavIWmAQ//S+7KLikImvqtNHIyKCUqNbiMEbGfgnGQSK1W/EUl
0+aR62vz055SvtnIafEFFlLz6jlSe/zzfzAhgJIXMw/oxwKBsk77vJqyG8Ng
LGz2YexQGSaiT2zDouNqISUtNwKSFSuSIHnoV3OMG4VVLDIOtfvwZCazxS3a
ct37u9vWwqj5wgAEBH1C63JvtMtyoABvMHUyvmYAQInoi5LYmRTfmSqlbI1Y
/M0cNjUQ1Pg6lmRJAjmPRMipX3sVoSHnJpEHq0L3hDcFDU846TTn3nAMyrhE
405f3xo5yrJVf+/Wwx2YZDMkvH4awFBF7Iff6qzjipjOC89pUmTzQsWBsIw/
Aede2C09YLKBO7x+6py6bFGJEmAw5Uf2bMl3JuzuJW5xp/Ypydx8oi1Erd45
4H2RXiIkh4o86zw1SdayT2XYsuNvWAGvElZkauuv9TEuhDZ8JNKEo1vjDCv6
YKMBUwLTJbz6nycVrRt5mPEbs+U+WgfaEuIy2yDhHg/Z/Lx2v6kAGfEcavmA
Ay/2Cmz8tyvbinC1Xh0NACSx3a9/ZerCZ7/4ij6MijrlivHiFgq0dQbxQxXQ
Z/2I0UKD4HxrTnkTNIPqG+LtEAm+MDCGXIMPB60G7y+7M9gqJR/TnNYdbjiJ
I0o1KoEsbLgnDtBBerZ7lotr+bP6Ox/X9HhCv1Cp4iTBwEwDnMn0hCkYgikB
B/4obrdmq9gWfPualBYhwQalYBhl4yBMlXfSUZB+d9f1kzYAzfycItbjx58O
s7P6cUcmYWf6WMGpovQkPzfVudqpw2mtLKZMIJvOW8jpoWACMW1NYghObfAt
aNB5Zjx4oP9D88QHVFmNtCiXdMH/INFSPdPt39dttCUGNjXPQ3N+98XTNve7
wP+LSWpCfAfeOToNqFrgBXmGQSUVTz6Rpbo+CZbneF7fBUPuRUIwes8wuVY/
RDtMwOrSCSoYnjEt/HlpJHjpoDGAYCdUktDRzBvWeuoIsr0FpqStRQsUs4Pl
xN/5RLIayD5I2nQu5MNMLY2JypZP+Xs7KXZyTWv9RY800sGIASpJgSlGUNxC
PVCeLD6l3hDuouSQwozNCYmE2Ie5DiwojWkCI+K2QJ4hIeQVJPzG3Ja4hMyv
GL3R2q6IHHkJP3G2QIhLHMNCjPuD4Ia8RxOVaODGVAprbkY1PEcZ6WwqGGmp
p/E/1p2gPVAPNzuCVXGa2Y8tuKD+XD27m7+Cp7qOgocgOBxgCDMR7xvzA7Zv
mNM3EcgD/nc6niBYlJQCc1xD9VnyVmOqQ0H+x03bqDEpB491iu8Yb03RPpRm
rIFNksuxqZr0elrHiopLL+NFFR96i/WtFmDErf2PI49SV3qXu4sLTg+BoTV5
FRKdpEhmFyPF8mefbw/4qPKBKMZVV+Ei5mVxr/39ERS4jCYU6tk6DpmvE0z/
j7D4f48XT8u7zLqxNdEOXgIN/pCjgjbHZ26UkUPge3GcslaOi4BKGnmXXwA3
orgSXbBHP/diXEbipUxw8c1NrUngfBc+UUcuWV5zSYrEA/0OBzXs9H5L189i
wNLge6FJre+oShezvC3kU9D+h5hQM6BE/bgHM+8K1kuzEDB9CcfrdJFRIiky
5793N782LSjnnmW1Y9KLyDKvExbbVmvy44DB4GlirCqz7OSt3799sASIenst
rGMSFQihvWkPP9zgv1ZXaL6mHBcmB78LGHvXEADbQ/P/p0r2h+okyriqT0IP
hLQ757nQEyTN8SweoIIXqAul7bBIwYFjKbZBsCADHmCsS7415Fn40vMQDV77
r2n+Q+GuVFrGCUJUIi6WE4VKqn0AxNLKKZvzRhlQGCEWqO8=
=CDn4
-----END PGP MESSAGE-----

**Comment by dashohoxha** [comment]
By the way, choosing the key with the latest expiry date is not guarantied to be correct.

**Comment by PiNotEqual3** [comment]
@dashohoxha 

> It is wrong to encrypt all the outgoing emails, without the consent of the recipent. Some people may  have lost their private key (or forgoten its password). In this case you are just sending them garbage. Some other people (like me), don't want to get all the emails encrypted, because they save most of the emails in order to search them later.

I think encryption should be easy and it could be easy if it's done the right way. All your reasons to not encrypt are software problems. Encryption should be the default when ever possible. 

If you lost your key or password, revoke it and ask to resend the mail. Well, the mail client could to all this automatically. Otherwise peoples will keep send you garbage and it would be your own fold.

Of course you need to search your mails. Your mail client need to handle this, it's on of it's main functions. If you can decrypt the mails to read them, you can also decrypt them for searching or store an encrypted search index. Or the client decrypt the mails and stores them with it's own encryption.

If there are multiple keys for a user use all of the if they are valid. He might uses different keys for his phone, his laptop and on his tablet.

I expect my mail client to search for a key automatically. All the key management should be done by the client. Maybe if you really really need to ask the user. It's all been done before and I can't understand why pgp can't do it but this is the reason it is not used everywhere.

**Comment by dashohoxha** [comment]
> I think encryption should be easy and it could be easy if it's done the
> right way. All your reasons to not encrypt are software problems.
> Encryption should be the default when ever possible.
>
I understand you. I remember myself thinking the same once upon a time.

**Comment by toberndo** [comment]
> find keys on key server, direct import
> automatic retrieval in encrypt dialog (non-persistent)?

Those two points form the initial issue post are now available with the Mailvelope key server
