### ISSUE TITLE
Transfer encrypted mail to Fastmail doesn't work

### ISSUE THREAD

**Issue by socketubs** [mailvelope/mailvelope#138]
Hi,

**Reproduce bug**:
When I write a mail, I have toolbox which appear, I choose to encrypt my message, I select the keys and clic on "Transfer".

Popup closed and I can see encrypted message in textarea but in fact when I send message, it's not encrypted.

But If i copy paste encrypted message from popup to textarea its ok.

How can I help to provide more information ?

**Comment by robmueller** [comment]
I'm one of the FastMail developers.

it will work if you enter any text in the textarea after inserting the encrypted message. Basically the problem is that mailvelope isn't generating an input event when entering the encrypted text into the editing textarea.

A cursory glance at the code suggests it should go at: mailvelope/common/ui/inline/encryptFrame.js:359 (after this._emailTextElement.val(msg);).
 
Something like the following should do the trick:
 
var event = document.createEvent( 'HTMLEvents' );
event.initEvent( 'input', true, true );
this._emailTextElement.dispatchEvent( event );

**Comment by toberndo** [comment]
@robmueller Thanks for the snippet!

It's now included in:
https://build.mailvelope.com/nightly/mailvelope.2015-05-27.chrome.zip
https://build.mailvelope.com/nightly/mailvelope.2015-05-27.firefox.xpi
