### ISSUE TITLE
Feature request - someway of toggling timeout on load

### ISSUE THREAD

**Issue by dbgdngit** [mailvelope/mailvelope#272]
I have a lot of keys which take a while to load so sometimes the extension doesnt load on launch.
You used to be able to manually tweak the timeout setting to 0 in require.js but content verification in Chrome now prevents that.
It would be nice to have a setting in options to disable timeout or extend more than 7 seconds.

**Comment by toberndo** [comment]
> I have a lot of keys which take a while to load so sometimes the extension doesnt load on launch.

The extension doesn't load at all? Or do you get an exception in the console?

> require.js but content verification in Chrome now prevents that

Could you elaborate more on this conclusion or provide a link? Would like to understand this better.

> It would be nice to have a setting in options to disable timeout or extend more than 7 seconds

If this problem is either related to require.js or Chrome content verification then I'm not sure how we can influence that. I will analyze if we can separate module loading and module initialization (e.g. loading of keys).

**Comment by toberndo** [comment]
Loading of the keyring is now defered in v0.12.0 and done in background.js after all modules are loaded. Think this should fix the timeout problem.

**Comment by dbgdngit** [comment]
spookily I was just looking at that and saw the new module and it does what you say.
