### ISSUE TITLE
Direct import Public Key from DNS

### ISSUE THREAD

**Issue by Tortue95** [mailvelope/mailvelope#290]
First, Thanks for this very good project !

it is possible to add a feeture to import public key from TXT record in the DNS ?

example with gpg:
 gpg --auto-key-locate pka -ea -r mail@exemple.com

Thanks for your great job

**Comment by rugk** [comment]
This old issue should be considered to be implemented into Mailevelope.
Because currently you can [import keys to your DNS](https://grepular.com/Publishing_PGP_Keys_in_the_DNS) [in many ways](http://www.gushi.org/make-dns-cert/HOWTO.html) and recently [mostly with help of Posteo](https://posteo.de/en/blog/new-posteo-public-key-directory) you can [do the same with S/MIME certs](http://www.heise.de/netze/meldung/DANE-Automatische-Mail-Verschluesselung-mit-S-MIME-3041530.html) (German article).

But to get back to PGP keys you basically have two ways: PKA (standardized in 2006) and OPENPGPKEY.
Because more recently the publication of PGP keys in the DNS was introduced by mail.de, who also created a [test site for this](https://openpgpkey.info/). [This](https://tools.ietf.org/html/draft-ietf-dane-openpgpkey-02) is the RFC of OPENPGPKEY.

More information:
* [Domain Name System speichert PGP-Schlüssel](http://www.golem.de/news/openpgpkey-domain-name-system-speichert-pgp-schluessel-1503-112927.html)

**Comment by wiktor-k** [comment]
Just for some context PKA ["will eventually be removed from gnupg"](https://lists.gnupg.org/pipermail/gnupg-users/2018-October/061034.html).

Werner suggests that "You should use the Web key Directory instead", that Mailvelope already has implemented in version 3 betas.

**Comment by toberndo** [comment]
Mailvelope v3.0 supports now the Web Key Directory. There are no plans to add further key discovery mechanisms via DNS (which would require a proxy like the Mailvelope key server anyway).
