### ISSUE TITLE
Improve usability of main browser extension dropdown

### ISSUE THREAD

**Issue by bnvk** [mailvelope/mailvelope#300]
Currently, the Mailvelope dropdown looks like this:

![screen shot 2015-04-06 at 4 45 30 pm](https://cloud.githubusercontent.com/assets/48677/7005917/03815842-dc7d-11e4-9c0e-432dad33ed1a.png)

I propose making the menu look like the following:

![dropdown widget](https://cloud.githubusercontent.com/assets/48677/7006293/42f67f36-dc80-11e4-8a18-c2bf4ba3b548.png)
- Add "Mailvelope" name makes widget more congruent UX with the tool that was downloaded
- Add `Key Ring` as it matches info architecture inside of Mailvelope extension
- Move `Options` and group with Key Ring
- Change word `Page` to `Provider` as it better expresses idea and is what is used inside of manager

I would be happy to work on implementing these suggestions if they are desired by the Mailvelope project owners!

**Comment by toberndo** [comment]
The main menu has been redesigned and looks now a bit different:

![Mailvelope main menu](https://cloud.githubusercontent.com/assets/1164474/24604289/7de62cdc-1864-11e7-9500-3baed5bb45de.png)

But there are still issues here:
- tooltips not working on Firefox
- unclear functionality of "Activated" checkbox. Do we need this at all?
- Current tab: reload button -> Probably not relevant for normal user?
- Options button: misleading, as this not only opens options/settings but also key ring management and the file encryption feature
- maybe add "Advanced" section to menu which is initially hidden

**Comment by comradekingu** [comment]
The new menu has too many concepts going on.

![mailvelopeui](https://cloud.githubusercontent.com/assets/13802408/26029518/0791a47e-3837-11e7-9aa3-c38ffb11f5c9.png)

- Options ordered in more logical manner
- Added "About", since "Help" isn't how you get to it, and it should be available.
(How you get to it is pressing "Options", where curiously what was help in the first menu, is now "Documentation", which would clear up the confusion were it called that in the first menu.
- "+ Add" is consistent with buttons elsewhere, but isn't as explanatory.
- New options icon used

1. If you want to temporarily disable otherwise, you run into https://github.com/mailvelope/mailvelope/issues/453
2. Don't know what reload does/when to use, i would assume it reloads the plugin, not the site.
3. Keyring being an option isnt clear, but it is management, as opposed to options, if you have the two. Or you could look in options for keyring management and assume "Keyring" to be just a display option.
4. Advanced isn't bad, but is it needed? Having more than needed is bad, but hiding it in a bad way is worse.
5. What is the point of "last activities"?

**Comment by bnvk** [comment]
May as well close this after all this time as some of my suggestions were implemented, others decided against. No need to keep it open.
