### ISSUE TITLE
0.13.0 - "Encrypt for" fields empty

### ISSUE THREAD

**Issue by quantum-x** [mailvelope/mailvelope#305]
After the automatic (ugh) upgrade to 0.13.0 - The recipient fields are empty, despite the plugin having my keys (and my other stored keys) in the settings dialog.

![image](https://cloud.githubusercontent.com/assets/2514540/7155248/8012ab04-e35d-11e4-92a5-7636d6752fd1.png)

**Comment by toberndo** [comment]
Fixed with https://github.com/mailvelope/mailvelope/releases/tag/v0.13.1

**Comment by quantum-x** [comment]
Thanks!

**Comment by quantum-x** [comment]
@toberndo What are the standard delays before this will be available in the Chrome Store etc?
Are there any work arounds until this point?

**Comment by toberndo** [comment]
@quantum-x since Mailvelope's first release in the Chrome Web Store all releases were available within 60 minutes. I'm not sure what causes now the delay and opened a support ticket in the Web Store.

A workaround is to set a primary key in your keyring or remove the flag "Always add primary key to list of recipients" in the settings. This should solve the issue.

**Comment by quantum-x** [comment]
Much appreciated, thank you.
