### ISSUE TITLE
[VULNERABILITY] Encryption Disables Signing

### ISSUE THREAD

**Issue by nixiepixel** [mailvelope/mailvelope#310]
#### Exploit Scenario

The UI will cause user to unknowingly send an unsigned message, allowing an attacker to modify the message in transit.
#### Details

When clicking the "Encrypt" button the "Sign" button disappears. This causes a user to believe the message is protected when it is not. There's no way for the user to know what cryptographic operations have taken place. This form of vulnerability is described in [CWE-655: Insufficient Psychological Acceptability](https://cwe.mitre.org/data/definitions/655.html).

**This is a serious security issue**, with multiple unresolved feature requests (#183 and #184) and a branch ([sign_and_encrypt](https://github.com/mailvelope/mailvelope/tree/sign_and_encrypt)) with this feature which is now over a year old.

Confidentiality without integrity is like cookies without milk.  ;-)
#### Reproduction

Firefox Plugin 0.12.1 - Latest available as of Apr. 9, 2015

Before clicking Encrypt
![screen shot 2015-04-22 at 1 02 31 am](https://cloud.githubusercontent.com/assets/10353016/7269767/8bc6e6bc-e88b-11e4-84dc-196c342ed45d.png)

After encrypting, no option to sign - only transfer
![screen shot 2015-04-22 at 1 03 12 am](https://cloud.githubusercontent.com/assets/10353016/7269769/90ef8d7e-e88b-11e4-8b16-8691bebd0589.png)

**Comment by Zimmi48** [comment]
+1
In my opinion, this is the most important missing feature together with the inability to check the signature of sender for encrypted mails.
Before this is corrected, I will advise people use Mailvelope only to sign their messages and check signatures (which is already great, thank you for that).

**Comment by toberndo** [comment]
Agree we should add support for signed and encrypted messages. But was not aware that the current UI seems to be confusing: you can either encrypt OR sign. Those are action buttons, not the toggle buttons that you might know from Enigmail.
This clear separation is intentional: a first cleartext signed and then encrypted (or worse, first encrypted and then cleartext signed) is not a "signed message" as defined in RFC4880 and would cause compatibility issues.
Hope we can soon add support for proper signing and verification of encrypted messages.

**Comment by safaci2000** [comment]
I was trying to read over the RFC, I think I understand why the UI behaves the way it does, but it would be nice if we can make it obvious that encryption + signature which is essentially what is needed for full trust to be established.   signature ensures integrity of the payload, and encryption ensures the privacy from prying eyes.

It would be nice to properly convey that full security is not yet implemented.  Maybe something as simple as adding a grayed out UI button for sign & encrypt. 

Though if the issue is coming soon (issue #184 ) then this might be a moot point.  

Just my 2 cents.

**Comment by amin007** [comment]
:smiley_cat:

**Comment by Br3ach** [comment]
+1 pretty much all clients out there support sign+encrypt

**Comment by thoucaed** [comment]
Throw away just for this.

PLEASE FIX THIS!

Add a new "sign & encrypt" button!

I have broken more than one email while trying to sign, then copy paste, and encrypt!

I'd also ask for an extra "paste public" button or checkbox.... but for now please fix the above!

**Comment by gjb** [comment]
Nothing seems to be happening with this. As it stands, Mailvelope is not of any use, unless you just want to send signed cleartext mail. Are there no plans to make this work?

**Comment by riton** [comment]
:+1: for this feature.

**Comment by ccatlett2000** [comment]
+1

Is there a status on this feature? As stated above, encryption is useless without signing for most use cases.

**Comment by toberndo** [comment]
@ccatlett2000 Once https://github.com/mailvelope/mailvelope/pull/394 is merged, we will add signing to the new editor layout. Scheduled for June.

**Comment by JakeChampion** [comment]
#394 was closed, where does that leave this issue?

**Comment by jmorahan** [comment]
#184 was just closed with the comment "Sign & encrypt is available in Mailvelope v1.6.0".

It still seems to *default* to not signing, but that can now be changed with a checkbox in the settings.

**Comment by toberndo** [comment]
Sign & encrypt is now available in Mailvelope v1.6.0
Please note that verification of signed & encrypted messages is currently only supported in Gmail, Yahoo and Outlook.com as we need provider specific logic to determine the sender email address which is a prerequisite for the verification step.
