### ISSUE TITLE
Not be able to switch the text editor

### ISSUE THREAD

**Issue by geokis** [mailvelope/mailvelope#336]
Hello,
I'm not sure if it is a bug or a problem with my browser setting. The issue appears in firefox and in chrome.
I can not switch between the editors. Both options are grey and not selectable.

![unbenannt](https://cloud.githubusercontent.com/assets/7952956/10300776/43dc0028-6bfb-11e5-9331-ae6b04196e18.png)

**Comment by zenima** [comment]
Yeah I came here because of this, too - couldn't find out why it's disabled. But seeing the [source code](https://github.com/mailvelope/mailvelope/blob/master/common/ui/settings/general.js), I think the feature is simply not finished yet..

**Comment by johnyb** [comment]
I also did a little research, because I missed this: Removed with 28da29add6095f3325d0a5e26a3869b622d8ffaa (reason: `Separate encryptFrame from editor`) and the Changelog for [v0.11.0](https://github.com/mailvelope/mailvelope/releases/tag/v0.11.0) states: `Deactivate rich-text editor as we currently only support PGP/Inline`
