### ISSUE TITLE
Silently failing if no signing key present

### ISSUE THREAD

**Issue by Manouchehri** [mailvelope/mailvelope#337]
When a signing subkey is missing from the private key ring, attempting to sign a message results in (literally) nothing happening. There should probably be an error message of some sort to explain the issue.

Not a big issue, but I thought I should file it anyway for future reference.

**Comment by dashohoxha** [comment]
I think it is a actually a big issue.
And I have noticed also that it gives you the option to sign with an expired key, and even it is the first one on the list of keys (maybe because it is the oldest?).
Should we create a new issue about this?

**Comment by Manouchehri** [comment]
@dashohoxha: Does it silently fail when you attempt to use an expired key, or does it actually sign it with the expired key?

**Comment by dashohoxha** [comment]
I don't know, because I have forgotten the password of the expired key. But it shows it on the list of keys when I try to sign a message, and it asks me for the password when select the expired key. Maybe it would fail afterwards, I am not sure.
However showing it in the list of available keys is for sure a bug, because it could easily filter it out by checking the expiration date.

**Comment by toberndo** [comment]
There is now a check included that only a valid key for signing can be selected.
