### ISSUE TITLE
addons.mozilla.org

### ISSUE THREAD

**Issue by foudfou** [mailvelope/mailvelope#338]
Hi, not an issue, rather a question out of curiosity: why isn't mailvelope not available on AMO anymore ?
Thank you for the great project !

**Comment by toberndo** [comment]
We tried to get reviewed in the AMO for over one and a half years. The review process is sort of problematic: aiming at identifying malicious add-ons, it can take weeks before your new version uploaded to AMO actually gets reviewed. The review as such is a formal process, which also includes criteria that are not security relevant but are required to simplify the review process such as: e.g. you can only use official builds of third party libraries like OpenPGP.js. In our case we use a fork of OpenPGP.js which is a show stopper. My experience is that you start to fix a certain problem only to get again rejected after two months for another one of the 180 issues identified by the automated validation process. I don't think there was single fix on the way to AMO acceptance that I did that was security relevant. At some some point you give up.

The situation has now changed with the add-on signing feature of Mozilla. You are now forced to get a review for your add-on, because you can't install the add-on from FF43 onwards without signing. But the review process is much simpler, Mozilla promises a reaction time of two days and less strict review rules, and this works most of the time according to my experience.

One thing changed with add-on signing: it's harder to have your add-on in AMO and at the same time self-hosted, because this scenario only works with two separate add-on IDs. Imagine now you have a security issue and tell your users: please update our add-on as soon as possible. For AMO you require weeks to get your review, but download from your website is no alternative because then the installation would not update existing versions from AMO but create a new duplicate add-on.

The current situation is: Mailvelope is only available at download.mailvelope.com, we are able to roll out updates within 1-5 days depending on the signing process.

Once WebExtensions for Firefox is available and Mozilla hopefully switches to a Chrome-like automated review process that allows to publish within 60min, we are happily coming back to AMO.

**Comment by Eagle3386** [comment]
IMHO, this should _never_ be the way to go. From my experience with about 400 open tabs (such a thing as Firefox' Panorama isn't available at Chrome nor does Google offer a 64-bit edition), Firefox consumed about 1/4 of Chrome's memory footprint.
That said, I desperately hope for the lowest convergence possible - it's Firefox not that Chrome douchebag after all!

However, the current signing process over at AMO isn't really acceptable - that's true, too. But having automated reviews is neither acceptable. Especially with security-related add-ons, I'd expect "manual" reviews more than ever.

Now, did you try to open a bug at Mozilla's Bugzilla in order to improve AMO for your specific case?

**Comment by rugk** [comment]
Mozilla improved the signing process again. So now it should really be easy. At first [no manual review may be required for signing anymore](https://blog.mozilla.org/addons/2015/12/01/de-coupling-reviews-from-signing-unlisted-add-ons/) and there is a [singing API](https://olympia.readthedocs.org/en/latest/topics/api/index.html) with which you can really automate this.

**Comment by toberndo** [comment]
@Eagle3386

> IMHO, this should never be the way to go. From my experience with about 400 open tabs (such a
> thing as Firefox' Panorama isn't available at Chrome nor does Google offer a 64-bit edition), Firefox
> consumed about 1/4 of Chrome's memory footprint.

Memory consumption is not relevant to the topic of this issue.

> But having automated reviews is neither acceptable. Especially with security-related add-ons, I'd 
> expect "manual" reviews more than ever.

Disagree to that, Mozilla cannot review the functional correctness of an add-on. That also applies to security related add-ons. Sandboxing as in Chrome Extensions and the new WebExtenions API of Mozilla helps to limit the impact of malicious add-ons.

@rugk 

> Mozilla improved the signing process again. So now it should really be easy. At first no manual
> review may be required for signing anymore and there is a singing API with which you can really 
> automate this.

Correct, but doesn't change the situation of getting your add-on hosted on addons.mozilla.org

**Comment by Eagle3386** [comment]
@toberndo 
> Disagree to that, Mozilla cannot review the functional correctness of an add-on. That also applies to security related add-ons. Sandboxing as in Chrome Extensions and the new WebExtenions API of Mozilla helps to limit the impact of malicious add-ons.

How come you know what they're doing internally? Especially, since Mozilla clearly stated that they expanded the review team due to staff bottlenecks. I would assume they do automatic tests as well as functional ones.

The WebExtensions API - from what I've read on Bugzilla - isn't even near where the the current one is regarding functionality and ways to manipulate Firefox. And all that because some Mozilla guys believe doing the same crap as Chrome will attract more users to the fox. I've never seen a product mimicking another one attracting more users than the original - but hey, history sometimes repeats itself.

Anyway, since I hate Chrome from the ground up, I'll just hope Firefox will be supported (again). Until then and regarding this discussion, I'm out. Thanks for taking the time, though.

**Comment by toberndo** [comment]
@Eagle3386 

> How come you know what they're doing internally? Especially, since Mozilla clearly stated that they 
> expanded the review team due to staff bottlenecks. I would assume they do automatic tests as well 
> as functional ones.

It's just impossible, they can't do functional testing. How should they for example guarantee that Mailvelope implements OpenPGP correctly?

> The WebExtensions API - from what I've read on Bugzilla - isn't even near where the the current one 
> is regarding functionality and ways to manipulate Firefox. And all that because some Mozilla guys 
> believe doing the same crap as Chrome will attract more users to the fox. I've never seen a product 
> mimicking another one attracting more users than the original - but hey, history sometimes repeats 
> itself.

I care more about security then functionality: a legacy Firefox add-on that is based on XPCOM has local access rights on your machine. It can basically do anything, that's why Mozilla has to put so much effort into the review process. It contract, the sandboxing in WebExtensions and Chrome Extensions is way better.

> I'll just hope Firefox will be supported (again).

Firefox was and will always be supported in Mailvelope.

**Comment by toberndo** [comment]
Mailvelope is back in AMO since version v2.2.0 (March 2018).
