### ISSUE TITLE
Stop using 32bit short-IDs in GUI

### ISSUE THREAD

**Issue by runn1ng** [mailvelope/mailvelope#415]
See link and discussion here

https://news.ycombinator.com/item?id=12296974

**Comment by toberndo** [comment]
We are only using the 64bit IDs in the UI. Only exception is the private key selection in the signing process where short IDs are ok.

**Comment by runn1ng** [comment]
I saw them in the public key selection in the encrypt window. But I might be wrong! Thanks for the answer.

**Comment by toberndo** [comment]
Right, used also in the public key selection. Reopening.

**Comment by toberndo** [comment]
Short key IDs are used as an additional identifier in the public key selection. So for the real world use case that you have multiple valid public keys for a certain email address you are able to distinguish them when selecting a recipient (although that is already bad UX, because who wants to memorize those cryptic 32 bit values? Anyway...).
In an attack scenario where two keys with a collision on the 32 bit key ID are imported into Mailvelope you would see two identical entries in the autocomplete list when choosing a recipient (public key).
My conclusions so far:
- replacing the 32 bit key ID with 64 bit key ID doesn't solve the problem: also 64 bit key IDs can be forged.
- the fingerprint is the only id that can be used for verification

**Comment by rugk** [comment]
> also 64 bit key IDs can be forged.

Ah, wait. But this is exponentially harder. Please don't try to argue in this way: "Y is not 100% proof and so I will just stay with the known insecure thing X."

Also have a look at https://evil32.com/. It's a pretty nice website.

**Comment by runn1ng** [comment]
> Also have a look at https://evil32.com/.

The ycombinator link in my OP is basically the same thing :)

**Comment by toberndo** [comment]
@rugk So where is your attack scenario on Mailvelope for "the known insecure thing X"? I argued that the use of the 32 bit key ID in the recipient autocomplete list of the public key selection is not critical. I'm pretty much open to the argument that it is better to not use the 32 bit value at all because there exist certain cases where it is critical and the user should not get accustomed to this data format. But from an UX perspective I see that the use of 64 bit values in the mentioned place above puts more "weight" on the UI.

**Comment by rugk** [comment]
Attack scenario: encrypt mail with wrong key?

So yes either remove it completely or switch to LongIDs.

**Comment by toberndo** [comment]
With 32bit: the user sees two entries in the list with the same short key id.
With 64bit: the user sees two entries in the list with different key id.

In both cases the normal user does not know what to do. In the best case they realize that something is wrong.

=> 64 bit key does not solve the problem in this specific case in Mailvelope
=> the key selection by choosing a recipient in the editor is not the right place for key verification. The 64 bit key ID is also not suitable for key verification.

**Comment by rugk** [comment]
Yes, so why not just remove it?

**Comment by toberndo** [comment]
in v1.6.0 now only 64bit key IDs used in the recipient selection and private key selection of signing.
