### ISSUE TITLE
Web extensions are the future

### ISSUE THREAD

**Issue by rugk** [mailvelope/mailvelope#461]
The current plan is that Firefox 57 will only support [web extensions](https://wiki.mozilla.org/WebExtensions). Your add-on is not a web extension yet as far as I can see, so you should consider remaking your add-on. The Firefox 57 release is [planned for 28th November 2017](https://wiki.mozilla.org/RapidRelease/Calendar).
Already for Firefox 53 (planned release: 18th April 2017) it is planned to no longer accept other new add-on submissions than web extensions on AMO (addons.mozilla.org). Old extensions can however still be updated.
The good message is that one should be able to use your web extensions add-on in all mayor browsers. That's the idea behind web extensions.

Note that all dates are estimates and may be changed.

German source: https://www.soeren-hentzschel.at/firefox/firefox-57-mit-exklusiver-webextension-unterstuetzung/
Original source: https://blog.mozilla.org/addons/2016/11/23/add-ons-in-2017/

**Comment by andymckay** [comment]
I note that the addons-linter doesn't throw up any errors on the Chrome version of the extension and I ran it in Firefox and so far haven't encountered any issues. I don't know all the features of the extension yet, but if there's anything from the Chrome API that is missing or different, please file a bug at https://bugzilla.mozilla.org/enter_bug.cgi?product=Toolkit

**Comment by rugk** [comment]
Indeed this is already a web extension. Don't know why I overlooked this when opening the issue.

**Comment by andymckay** [comment]
The Firefox version listed here: https://github.com/mailvelope/mailvelope/releases/download/v1.6.5/mailvelope.firefox.xpi isn't a WebExtension though, its an SDK extension. Presumably using code here: https://github.com/mailvelope/mailvelope/tree/master/src/firefox

So I think the code is all there, but it just needs testing on Firefox (along with how the update from SDK to  WebExtension would happen).

**Comment by rugk** [comment]
Okay, now I know why I've opened this issue. Thanks for reminding me. 😂

**Comment by toberndo** [comment]
@andymckay Thanks for testing. Good to know the Chrome version works already with the WebExtensions API. Our plan is to first release an [embedded WebExtension](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Embedded_WebExtensions) version of Mailvelope and migrate the keyring stored in the simple storage (Add-on SDK) to a storage in the WebExtension context. As a second step we would release a full WebExtension version of Mailvelope that has direct access to the previously migrated keyring.
One issue that we currently have with the simple storage solution of the Add-on SDK is data loss of the Mailvelope keyring (https://bugzilla.mozilla.org/show_bug.cgi?id=1091244) and we want to make sure that this is fixed with the new WebExtension API. So can we be sure that the storage API of WebExtension (https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/storage) does not have the same data loss issue as its Add-on SDK counterpart? An alternative would be to migrate to IndexedDB instead (given that this is stable).

**Comment by andymckay** [comment]
I haven't seen any reports of data loss in chrome.storage.local. But this is software, sadly there's always bugs :(

**Comment by toberndo** [comment]
@andymckay I checked today and I'm still not able to load iframes on a host page with content from a WebExtension, see: https://bugzilla.mozilla.org/show_bug.cgi?id=792479#c78
This has been a major obstacle in developing Mailvelope for Firefox and sadly it seems this is still not fixed with WebExtensions.

**Comment by rugk** [comment]
@toberndo I think Web Extensions have their own CSP by default.

**Comment by rvandermeulen** [comment]
FWIW, this addon is now completely non-functional on Firefox 57 nightly builds. Is there a prerelease version of the webext version available for testing somewhere? I'd be happy to volunteer to do so if the answer is yes!

**Comment by toberndo** [comment]
A first beta version of Mailvelope as a Firefox WebExtension is now available:

https://download.mailvelope.com/releases/v1.9.2b

This contains a signed XPI package which can be installed in all Firefox >=52.

Changes in this 1.9beta are quite large with lots of refactoring:
- Reimplement large parts of the main UI (Keyring Management and Options) with React
- Migrate to OpenPGP v2.5
- Migrate to Firefox WebExtension API
- ES6

Testing is highly appreciated. If you update to 1.9b in Firefox make sure to have Mailvelope >=1.8.0 installed, otherwise the keyring gets lost.

**Comment by rvandermeulen** [comment]
Thanks for the link! So far, it's working great and feels a lot more responsive to boot!

**Comment by fosy** [comment]
Works! Tried it on Firefox Developers Edition 57.0b1 (64-bit) today. 
with https://download.mailvelope.com/releases/v1.9.6b/

![image](https://user-images.githubusercontent.com/12451323/30664996-dcf23f24-9e4f-11e7-96dd-af34ae06a833.png)

Thanks a lot!

**Comment by toberndo** [comment]
Released as v2.0.0
Thanks everyone for testing.
