### ISSUE TITLE
UX/wording: "Encrypt attachments"

### ISSUE THREAD

**Issue by mdik** [mailvelope/mailvelope#492]
Hi,

I am not completely happy with the choice of "Encrypt attachments" in the message editor, because it is not about encrypting attachments, but encrypting files.

Calling it "Encrypt attachments" creates the false expectation that either already attached files will be encrypted, or that files that are chosen will be attached. Neither of that will happen.

Renaming it to "Encrypt files" would also be more consistent with the choice of words in the Mailvelope Options dialog.

A compromise may be "Encrypt files for attachment".

Sincerely,

Malte

**Comment by mdik** [comment]
@toberndo What does up-for-grabs mean? Because there was no support voiced for any of my suggestions, so even **if** I'd want to grab the issue, I wouldn't know which phrasing to go with :sweat_smile:

**Comment by toberndo** [comment]
My initial thought on this was that the user is here in the "Compose email" context and therefore "Add attachments" is what they are actually looking for. We don't provide that, but giving a link to "Encrypt attachments" leads the user to the right place where this action can be conducted.
We discussed this scenario also at an IFF UX workshop, and the "Encrypt attachments" link was not questioned, but people wanted to change the "File Encryption" in the top navigation of the main app to "Attachments", maybe with a note below: you can also use this for file encryption. Which I was not so happy about, because I wanted to keep the more general term "File encryption" because it can be also used in other scenarios besides email.
Not sure how "Encrypt files for attachment" sounds for native speakers.
So this topic has some history with contradicting opinions and I thought I put it "up-for-grabs" if someone finds the silver bullet 😀

**Comment by mdik** [comment]
There probably is none, but I'd change it to "Encrypt files", and see how it goes :woman_shrugging:

**Comment by toberndo** [comment]
Sounds good, renamed in https://github.com/mailvelope/mailvelope/commit/3d537ea19b649bc19465d74157214d6c95bb4fd3

**Comment by mdik** [comment]
Cool. Thank you!
