### ISSUE TITLE
Bring WebExtension to addons.mozilla.org

### ISSUE THREAD

**Issue by rugk** [mailvelope/mailvelope#539]
Followup of (interestingly open, but locked) issue https://github.com/mailvelope/mailvelope/issues/338.

So yet another advantage of the new WebExtension structure is that Mozilla is publishing new addons much faster now.

> Add-ons built on the WebExtensions API will now be automatically reviewed. This means we will publish add-ons shortly after uploading.

https://blog.mozilla.org/addons/2017/09/21/review-wait-times-get-shorter/

-----

So now you can bring it back addons.mozilla.org (AMO). You do not need any custom update mechanism anymore and everything is fine! :tada: 

/cc @foudfou, @Eagle3386,

**Comment by toberndo** [comment]
Current status is that Mailvelope 2.1.1 is approved in AMO since 20th Dec, but not yet fully reviewed. Only with a full review we will get a stable download URL for the add-on as well as separate beta and release channels.

Seems like others having problems with long review times as well: https://discourse.mozilla.org/t/excessive-queue-times-for-reviews-waiting-since-nov-26/24321

The reviewer for Mailvelope does currently not respond to email.

Overall this reminds me of the frustrating review situation 2-3 years ago (https://github.com/mailvelope/mailvelope/issues/338#issuecomment-151908036) and is not really encouraging developers to switch from self-hosting to AMO (which is practically an irreversible step).

**Comment by rugk** [comment]
Aha, so as the user commented on the thread you linked, the issue is you minified the js code. 

Basically the addon is already downloadable, just not listed, because of the minified code.

**Comment by toberndo** [comment]
Stable download URL is now available: https://addons.mozilla.org/firefox/downloads/latest/mailvelope/

All download links on website point to addons.mozilla.org. Update to Mailvelope 2.1.1 currently running, after that self-hosting is no more.

**Comment by rugk** [comment]
Is that possible to update from the self-hosted version to the AMO one? If so, it would be great...

**Comment by toberndo** [comment]
@rugk Yes, in the 2.1.1 update there is no more
`"update_url": "https://download.mailvelope.com/update/mailvelope.firefox.webex.xml"`
in the manifest file. Therefore Firefox will check for updates only on addons.mozilla.org.
