### ISSUE TITLE
Add support for advanced WKD key discovery

### ISSUE THREAD

**Issue by aagor** [mailvelope/mailvelope#774]
Mailvelope can already fetch keys via the direct method of Web Key Directory (WKD).
But the WKD standard also defines a advanced method described [here](https://datatracker.ietf.org/doc/html/draft-koch-openpgp-webkey-service-12#section-3.1).

The standard says, that the advanced method should be preferred to the direct method and should be tried first.
The only difference between both methods is the URL: (using test-wkd@metacode.biz as example mail)
* advanced method: https://openpgpkey.metacode.biz/.well-known/openpgpkey/metacode.biz/hu/4hg7tescnttreaouu4z1izeuuyibwww1?l=test-wkd
* direct method: https://metacode.biz/.well-known/openpgpkey/hu/4hg7tescnttreaouu4z1izeuuyibwww1?l=test-wkd for the direct method.

**Comment by c8k** [comment]
Like mentioned [here](https://wiki.gnupg.org/WKD/Misc) I will write my bachelor thesis about Web Key Directories. It would be great if someone of @mailvelope could assign this task to me because I'm going to implement this feature in at least one email client  anyway.

**Comment by toberndo** [comment]
@c8k great news! I assigned this task to you.

**Comment by c8k** [comment]
I added a part, where Mailvelope should try to resolve the DNS name of the domain part of the email. To try to resolve the name is a better way to check, if the subdomain exists than using the fetch method because the WKD server could be offline, although there is a DNS entry.

**Comment by c8k** [comment]
When DNS resolving is not possible, Mailvelope will now first try the advanced method and only when a NetworkError occures, it will try the direct method. When no NetworkError occures, a server is available and the DNS name can be resolved, so it is not allowed to use the direct method.
After making these changes I tested the extension on Firefox with different emails, where I knew what the result should be and it worked fine. On Chrome sadly not and I don't know why :(

**Comment by bernhardreiter** [comment]
> On Chrome sadly not and I don't know why

Can say more about the symptoms? What call is failing and how?
(One method is to spread many console.log() calls in there, until you know what is going on. To be removed later of course.
Another method is to try to execute all call manually in the console for easier inspection, but there may be a difference to console execution or execution in a browser extension.)

**Comment by c8k** [comment]
> Can say more about the symptoms? What call is failing and how?
[...] Another method is to try to execute all calls manually in the console for easier inspection, but there may be a difference to console execution and execution in a browser extension.)

When I call
`fetch('https://openpgpkey.wkdtest.ntvtn.de/.well-known/openpgpkey/wkdtest.ntvtn.de/hu/u39nzhjet98booeha9jxjqoia1kraqzh?l=kim_luca.ross-mueller')`
, while I have duckduckgo.com open in the actual tab, I get the following errors:

`Refused to connect to 'https://openpgpkey.wkdtest.ntvtn.de/.well-known/openpgpkey/wkdtest.ntvtn.de/hu/u39nzhjet98booeha9jxjqoia1kraqzh?l=kim_luca.ross-mueller' because it violates the following Content Security Policy directive: "connect-src https://duckduckgo.com https://*.duckduckgo.com https://3g2upl4pq6kufc4m.onion/ https://duckduckgogg42xjoc72x3sjasowoarfbgcmvfimaftt6twagswzczad.onion/ filesystem: about: blob: ws: wss: chrome-search:".`

`Refused to connect to 'https://openpgpkey.wkdtest.ntvtn.de/.well-known/openpgpkey/wkdtest.ntvtn.de/hu/u39nzhjet98booeha9jxjqoia1kraqzh?l=kim_luca.ross-mueller' because it violates the document's Content Security Policy.`

> (One method is to spread many console.log() calls in there, until you know what is going on. To be removed later of course.

Unfortunately, when I build the extension for Chrome (or Firefox), the console.log outputs will not be shown in the console. For Firefox I can use the command
`node_modules/web-ext/bin/web-ext run --source-dir=./build/firefox`
to test the extension in some kind of dev version with console outputs, but I don't know how to test it on Chrome.

**Comment by c8k** [comment]
I don't know why, but the problem disappeared suddenly. Also, toberndo explained me via mail, how to test on Chrome with console.log (need to open the background page, which can be opened from the extension window in Chrome).
Finally I was able to make a fix for Chrome. I also tested again with different emails and WKD works fine now.

**Comment by c8k** [comment]
Because the linking of the Pull Request with this Issue didn't work, here is the link to the Pull Request: https://github.com/mailvelope/mailvelope/pull/782
