### ISSUE TITLE
Sending e-mail to myself and getting Key not found!

### ISSUE THREAD

**Issue by mloskot** [mailvelope/mailvelope#827]
I'm using the Mailvelope in Firefox with GMail.

I have imported my own pair of private and public keys to Mailvelope.
I can decrypt with Mailvelope received e-mails sent to myself from other clients e.g. Outlook with GpgOL add-in.

However, I can not encrypt any e-mails to myself:

![image](https://github.com/mailvelope/mailvelope/assets/80741/39962552-31ab-4ac3-a969-0b80c5d57193)

I have tried both backends, OpenPGP.js and GnuPG.

I tried to find answer to my problem in the FAQ and existing issues, but without any luck.

**Comment by systemplatine** [comment]
Your problem is relatively easy to identify thanks to the images you sent: Mailvelope no longer accepts keys using the DSA algorithm with this length. You would need to generate new keys with RSA or ECC Curve 25519 algorithms.
Yes, I know it's shown als "valid" in the key details. We're aware on this and working on it.

**Comment by mloskot** [comment]
@systemplatine Thank you very much! I'm happy to close this issue as solved.
