### ISSUE TITLE
Extension not displaying text-authoring window in Synology Mail PLUS application

### ISSUE THREAD

**Issue by springcomp** [mailvelope/mailvelope#828]
It seems the Mailvelope extension is not supporting the [Synology Mail PLUS application](https://www.synology.com/fr-fr/dsm/feature/mailplus).

When authoring a new email, the Mailvelope authoring window does not appear.
Likewise, when reading an encrypted email, Mailvelope does not offer to decrypt the message.

Is there any pointers for how I could help debug the behaviour of the extension ?

**Comment by systemplatine** [comment]
Are you sure you [authorized](https://mailvelope.com/faq#not_on_list) the domain? 
This may help also: [Get started](https://mailvelope.com/help) Step 5 choose "Other providers"

**Comment by springcomp** [comment]
Yes indeed I did authorize the domain and followed the instructions to reload Mailvelope and the website. I should have made it clear in the issue.

This is using Firefox 120 and Firefox Portable 115.

**Comment by rimmer** [comment]
Tried with `dsmdemo.synologydemo.com` and I can confirm it doesn't work. 
Considering another issue with custom domain authorization #838 I am going to file an internal ticket to check if there is an issue with domain auth.
This issue is quite old, but for newer users of Synology Mail PLUS I'd like to point out that it has it's own PGP encryption implementation. Hence, we probably won't be investigating too much if the issue is Synology specific.
