### ISSUE TITLE
Authorized Domains for custom port not working

### ISSUE THREAD

**Issue by SuperdukeGates** [mailvelope/mailvelope#838]
In windows 10 firefox 125.0.1 and mailvelope 5.1.2.

I have a roundcube server like this: `https://roundcube.example.com:12345` I added this domain by **Authorize this domain** button and append `:12345` on the domain pattern.

Then reload mailvelope and roundcube, the rounccube still cannot detect the mailvelope.

I tried to enable **API** for this roundcube domain pattern but still not working.

**Comment by rimmer** [comment]
Hi, thanks for reporting. Did you try without appending port?

**Comment by rimmer** [comment]
I filed an internal issue for this, we are going to check and get back here (not necessarily soon 🥲 )

**Comment by rimmer** [comment]
Hi, I've checked it against `localhost:8000` with local roundcube instance and it works. I may assume that the roundcube version you use it just old without mailvelope integration. Is it possible? I am gonna later check against `something.local:8000` to be sure, but since no one else reported this, I am closing.
